ALCPT_Online_Platform/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('alcpt.urls')),
    path('', include('registration.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

unit/urls.py
from django.urls import path, include

from unit.views import UnitListView, SchoolCreate, CollegeCreate, DepartmentCreate, SquadronCreate

urlpatterns = [
    path('unit/', include([
        path('list', UnitListView.as_view(), name='unit_list'),
        path('new-school', SchoolCreate.as_view(), name='create_school'),
        path('new-college', CollegeCreate.as_view(), name='create_college'),
        path('new-department', DepartmentCreate.as_view(), name='create_department'),
        path('new-squadron', SquadronCreate.as_view(), name='create_squadron'),
    ]))
]

notification/models.py
from django.db import models

from registration.models import User
# Create your models here.


# Used to notify something important or need to know to the users
class Notification(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    is_read = models.BooleanField(default=False)
    is_public = models.BooleanField(default=False)
    recipient = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    announcer = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='created_by')
    created_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_time']

    def __str__(self):
        return self.title

templates/base.html
<!DOCTYPE html>
<html lang="en">

{% include 'head.html' %}

<title>
    {% block title %}
    {% endblock %} - ⌘｜ALCPT Online Platform
</title>

{% include 'header.html' %}

<body>
    {% block main %}
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-2">
                    <div class="container">
                        <div class="row">
                            {% block sidebar %}
                            {% endblock %}
                        </div>
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="container">
                        <div class="row justify-content-center">
                            {% block content %}
                            {% endblock %}
                        </div>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="container">
                        <div class="row">
                            {% include 'messages.html' %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endblock %}
</body>

{% include 'footer.html' %}

</html>

{% block script %}
{% endblock %}

templates/footer.html
<div style="margin: 5rem"></div>
<footer class="fixed-bottom bg-dark">
    <div class="footer-copyright text-center py-2 text-white">
        ALCPT © 2019 Information Management, College of Management, NDU
    </div>
</footer>

templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <!--Copy from Licht, but don't know what does it work-->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!--CSS-->
{#    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">#}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'bootstrap-4.4.1-dist/css/bootstrap.css' %}">

    <!--javascript-->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script rel="script" src="{% static 'js/jquery-3.4.1.slim.min.js' %}"></script>
    <script rel="script" src="{% static 'bootstrap-4.4.1-dist/js/bootstrap.min.js' %}"></script>

    <style>
        .card {
            box-shadow: 0 4px 8px #E3E7EB;
        }
        #sidebar a{
            text-decoration: none;
        }
    </style>
</head>

templates/header.html
{% load registration_filters %}

<header>
    <nav class="navbar navbar-expand-lg navbar-light navbar-laravel" style="background-color: #4CCABD">
        <div class="container">
            <a class="navbar-brand text-dark" href="{% url 'index' %}">⌘︎｜ALCPT Online Platform</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <!--Navbar-->
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">
                    {% if user.is_authenticated %}
                        {% include 'privilege_navbar.html' %}

                        {% include 'user_functions_menu.html' %}

                        {% include 'notification_center.html' %}
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="{% url 'login' %}">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="{% url 'sign_up' %}">Sign up</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</header>

templates/index.html
{% extends 'base.html' %}

{% block title %}Index{% endblock %}

{% block main %}
    <main>
        <div class="jumbotron">
            <h1 class="display-4" style="font-weight: 400;">Welcome to ALCPT Online Platform</h1>
            <p class="lead">This is a place where we try to build some interesting stuff about a web system for ALCPT. Hope you can improve your ability of English via this system.</p>
            <hr class="my-4">
            <p>If you have any suggestions, please leave us a message. Thank you for your using.</p>
            <a class="btn btn-primary" href="#contact-us" data-toggle="tooltip" data-placement="top" title="Contact Us">Contact Us</a>
            <a class="btn btn-secondary" href="#download_system_pdf" data-toggle="tooltip" data-placement="top" title="Download System PDF">About System</a>
            <a class="btn btn-light" data-toggle="modal" data-target="#ModalOperationManual">Operation Manual</a>

            <div class="modal fade" id="ModalOperationManual" tabindex="-1" role="dialog" aria-labelledby="ModalCenterTitle" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div class="modal-header text-center">
                            <h5 class="modal-title" id="ModalLongTitle">Operation Manual</h5>
                        </div>

                        <div id="modal-menu">
                            <ul class="list-inline text-center">
                                <li class="p-3 border-bottom" style="cursor: pointer" onclick="alert('Function is developing. Stay tuned.🤪');">System</li>
                                <li class="p-3 border-bottom" style="cursor: pointer" onclick="alert('Function is developing. Stay tuned.🤪');">User</li>
                                <li class="p-3 border-bottom" style="cursor: pointer" onclick="alert('Function is developing. Stay tuned.🤪');">Report</li>
                                <li class="p-3 border-bottom" style="cursor: pointer" onclick="alert('Function is developing. Stay tuned.🤪');">System Manager</li>
                                <li class="p-3 border-bottom" style="cursor: pointer" onclick="alert('Function is developing. Stay tuned.🤪');">Test Manager</li>
                                <li class="p-3 border-bottom" style="cursor: pointer" onclick="alert('Function is developing. Stay tuned.🤪');">TB Manager</li>
                                <li class="p-3 border-bottom" style="cursor: pointer" onclick="alert('Function is developing. Stay tuned.🤪');">TB Operator</li>
                                <li class="p-3 border-bottom" style="cursor: pointer" onclick="alert('Function is developing. Stay tuned.🤪');">Viewer</li>
                                <li class="p-3 border-bottom" style="cursor: pointer" onclick="alert('Function is developing. Stay tuned.🤪');">Testee</li>
                                <li class="p-3" style="cursor: pointer" onclick="alert('Function is developing. Stay tuned.🤪');">Download Operation Manual</li>
                            </ul>
                        </div>

                        <div class="modal-footer">
                            <a class="btn btn-secondary" style="color: white" data-dismiss="modal">Cancel</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

templates/message_window.html
{% if messages %}
    {% for message in messages %}
        {% if message.tag == 'success' %}
            <div id="prompt">
                <div class="alert alert-success" role="alert">
                    <i class="fa fa-window-close" aria-hidden="true">{{ message }}</i>
                </div>
            </div>
        {% elif message.tag == 'warning' %}
            <div id="prompt">
                <div class="alert alert-warning" role="alert">
                    <i class="fa fa-window-close" aria-hidden="true">{{ message }}</i>
                </div>
            </div>
        {% elif message.tag == 'error' %}
            <div id="prompt">
                <div class="alert alert-danger" role="alert">
                    <i class="fa fa-window-close" aria-hidden="true">{{ message }}</i>
                </div>
            </div>
        {% endif %}
    {% endfor %}
{% endif %}

<script type="text/javascript">
    setTimeout(function(){
        $('#prompt').hide()
    }, 5000)
</script>

templates/messages.html
<div class="col-md-12">
{% if messages %}
    {% for message in messages %}
        {% if message.tags == 'success' %}
            <div id="prompt" class="card my-4 text-left alert-success prompt">
                <a class="card-header"><i class="fa fa-window-close" aria-hidden="true"> {{ message }}</i></a>
            </div>
        {% elif message.tags == 'warning' %}
            <div id="prompt" class="card my-4 text-left alert-warning prompt">
                <a class="card-header"><i class="fa fa-window-close" aria-hidden="true"> {{ message }}</i></a>
            </div>
        {% elif message.tags == 'error' %}
            <div id="prompt" class="card my-4 text-left alert-danger prompt">
                <a class="card-header"><i class="fa fa-window-close" aria-hidden="true"> {{ message }}</i></a>
            </div>
        {% endif %}
    {% endfor %}
{% endif %}
{#{% if form.errors %}#}
{#    {% for field in form %}#}
{#        {% for error in field.errors %}#}
{#            <div class="card my-4 text-left alert-danger prompt">#}
{#                <a class="card-header"><i class="fa fa-window-close" aria-hidden="true"> {{ error|escape }}</i></a>#}
{#            </div>#}
{#        {% endfor %}#}
{#    {% endfor %}#}
{#    {% for error in form.non_field_errors %}#}
{#        <div class="card my-4 text-left alert-danger prompt">#}
{#            <a class="card-header"><i class="fa fa-window-close" aria-hidden="true"> {{ error|escape }}</i></a>#}
{#        </div>#}
{#    {% endfor %}#}
{#{% endif %}#}
{#</div>#}

<script type="text/javascript">
    setTimeout(function(){
        $('.prompt').hide()
    }, 5000)
</script>

templates/notification_center.html
{% load notification_filters %}

<button type="button" class="btn" data-toggle="modal" data-target="#NotificationCenter">
    <i class="fa fa-bell"></i>
    {% if request.user|notification_unread_amount != 0 %}
        <label class="notification-custom"><sup>{{ request.user|notification_unread_amount }}</sup></label>
    {% endif %}
</button>

<div class="modal fade" id="NotificationCenter" tabindex="-1" role="dialog" aria-labelledby="NotificationCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header text-center">
                <h5 class="modal-title" id="ModalLongTitle">Notification Center(Total:{{ request.user|notification_center_amount }})</h5>
            </div>

            <div id="modal-menu">
                <ul class="text-center list-inline">
                    {% for notification in request.user.notification_set.all %}
                        <li class="border pt-1 pb-1">
                            <ul class="text-left list-inline pl-3">
                                <li>Title: {{ notification.title }}</li>
                                <li>Content: {{ notification.content|linebreaks }}</li>
                                <li class="text-muted">-by {{ proclamation.created_by }} in {{ proclamation.created_time }}</li>
                            </ul>
                        </li>
                    {% empty %}
                        <li class="pt-3 pb-3">No notification recently</li>
                    {% endfor %}
                </ul>
            </div>

            <div class="modal-footer">
{#                <button type="button" class="btn btn-secondary" onclick="set_action('read');">Read</button>#}
{#                <button type="button" class="btn btn-light" onclick="set_action('delete');">Delete</button>#}
                <a class="btn btn-secondary" style="color: white" data-dismiss="modal">Cancel</a>
            </div>
        </div>
    </div>
</div>
<style type="text/css">
    .notification-custom{
        width: 15px;
        height: 15px;
        background-color: red;
        border-radius: 24px;
        color: white;
        text-align: center;
    }
</style>

templates/privilege_navbar.html
{% load registration_filters %}

{% if request.user|has_permission:'SystemManager' %}
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            SystemManager
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'user_list' %}">User List</a>
            <a class="dropdown-item" href="{% url 'unit_list' %}">Unit List</a>
            <a class="dropdown-item" href="#reportcategory_list">ReportCategory List</a>
        </div>
    </li>
{% endif %}

{% if request.user|has_permission:'TestManager' %}
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            TestManager
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#exam_list">Exam List</a>
            <a class="dropdown-item" href="#test_paper_list">TestPaper List</a>
            <a class="dropdown-item" href="#testee_group_list">Testee Group List</a>
        </div>
    </li>
{% endif %}

{% if request.user|has_permission:'TBManager' %}
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            TBManager
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'TBManager_question_list' %}">Question List</a>
            <a class="dropdown-item" href="{% url 'TBManager_review_list' %}">Question Review</a>
        </div>
    </li>
{% endif %}

{% if request.user|has_permission:'TBOperator' %}
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            TBOperator
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'TBOperator_question_list' %}">Question List</a>
            <a class="dropdown-item" href="{% url 'question_creation' %}">New Question</a>
        </div>
    </li>
{% endif %}

{% if request.user|has_permission:'Viewer' %}
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Viewer
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#view_testee_score">View Testee Score</a>
        </div>
    </li>
{% endif %}

{% if request.user|has_permission:'Testee' %}
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Testee
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#testee_exam_record">Exam Record</a>
            <a class="dropdown-item" href="#testee_score_record">Score Record</a>
            <a class="dropdown-item" href="#listening_practice">Listening Practice</a>
            <a class="dropdown-item" href="#reading_practice">Reading Practice</a>
            <a class="dropdown-item" href="#integrate_practice">Integrate Practice</a>
        </div>
    </li>
{% endif %}

templates/user_functions_menu.html
<button type="button" class="btn text-dark" data-toggle="modal" data-target="#ModalCenter">
    <i class="fa fa-user"></i>
</button>

<div class="modal fade" id="ModalCenter" tabindex="-1" role="dialog" aria-labelledby="ModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header text-center">
                <h5 class="modal-title" id="ModalLongTitle">User: {{ request.user.username }}</h5>
            </div>

            <div id="modal-menu">
                <ul class="list-inline text-center">
                    <li class="p-3 border-bottom" style="cursor: pointer" onclick="window.location.href='{% url 'profile' %}'">Profile</li>
                    {% if request.user.student %}
                    <li class="p-3 border-bottom" style="cursor: pointer" onclick="window.location.href='{% url 'student_profile' %}'">Student Profile</li>
                    {% endif %}
                    <li class="p-3 border-bottom" style="cursor: pointer" onclick="window.location.href='{% url 'profile_edit' %}'">Profile Edit</li>
                    <li class="p-3 border-bottom" style="cursor: pointer" onclick="alert('Function is developing. Stay tuned.🤪');">My Note</li>
                    <li class="p-3 border-bottom" style="cursor: pointer" onclick="window.location.href='{% url 'album' %}'">Album</li>
                    <li class="p-3 border-bottom" style="cursor: pointer" onclick="alert('Function is developing. Stay tuned.🤪');">Email</li>
                    <li class="p-3 border-bottom" style="cursor: pointer" onclick="alert('Function is developing. Stay tuned.🤪');">Password Change</li>
                    <li class="p-3 border-bottom" style="cursor: pointer" onclick="alert('Function is developing. Stay tuned.🤪');">Real Exam Record</li>
                    <li class="p-3 border-bottom" style="cursor: pointer" onclick="alert('Function is developing. Stay tuned.🤪');">Report</li>
                    <li class="p-3" style="cursor: pointer" onclick="alert('Function is developing. Stay tuned.🤪');">About</li>
                </ul>
            </div>

            <div class="modal-footer">
                <a class="btn btn-light" href="{% url 'logout' %}" onclick="return confirm('Sure to logout?')">Logout</a>
                <a class="btn btn-secondary" style="color: white" data-dismiss="modal">Cancel</a>
            </div>
        </div>
    </div>
</div>